#!/usr/bin/env python
"""
    Generation configuration for pypucloud
    ======================================
"""
import argparse
import logging


parser = argparse.ArgumentParser()
parser.add_argument("env", choices=["local", "aws", "gcp"])


def main():
    args = parser.parse_args()
    logging.debug(f"Environment type is '{args.env}'")


if __name__ == "__main__":
    main()
