# --------------------------------------
# Playbook for init environment
# --------------------------------------
- hosts: localhost
  tasks:
    - name: Load config
      include_vars:
        file: "../config.yml"
    - name: "Gather facts of target CF stack"
      amazon.aws.cloudformation_info:
        stack_name: "{{ aws.stack_name }}"
        region: "{{ aws.region }}"
        aws_access_key: "{{ aws.access_key }}"
        aws_secret_key: "{{ aws.secret_key }}"
      register: cf_ret
    - set_fact:
        stack: "{{ cf_ret.cloudformation[aws.stack_name]|default(None) }}"
    - block:
        - name: "Setup stack (pre-requirements)"
          amazon.aws.cloudformation:
            stack_name: "{{ aws.stack_name }}"
            region: "{{ aws.region }}"
            state: "present"
            aws_access_key: "{{ aws.access_key }}"
            aws_secret_key: "{{ aws.secret_key }}"
            template: "./files/cloudformation-pre.yml"
            template_parameters:
              TableNamespace: "{{ aws.table_prefix }}"
          register: cf_ret
        - set_fact:
            stack: "{{ cf_ret }}"
      when: stack == ""
    - name: Build docker-image
      community.docker.docker_image:
        build:
          path: "../docker"
        name: "{{ stack.stack_outputs.ImageUri }}"
        source: build
        force_source: yes
    - docker_push_ecr:
        name: "{{ stack.stack_outputs.ImageUri }}"
        region: "{{ aws.region }}"
        aws_access_key: "{{ aws.access_key }}"
        aws_secret_key: "{{ aws.secret_key }}"
    - name: "Setup stack (all)"
      amazon.aws.cloudformation:
        stack_name: "{{ aws.stack_name }}"
        region: "{{ aws.region }}"
        state: "present"
        aws_access_key: "{{ aws.access_key }}"
        aws_secret_key: "{{ aws.secret_key }}"
        template: "./files/cloudformation-all.yml"
        template_parameters:
          TableNamespace: "{{ aws.table_prefix }}"
